backend:
  name: github
  repo: victor3spoir/victorespoir-contents
  branch: main
  base_url: https://auth.decapcms.org

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Articles"
    folder: "content/posts"
    create: true
    format: "frontmatter"
    extension: "md"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Contenu", name: "body", widget: "markdown" }
